# Generated by Django 5.0.4 on 2024-04-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
