# Generated by Django 5.0.4 on 2024-04-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
